name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Server Dependencies
        working-directory: server
        run: npm ci
      - name: Install Client Dependencies & Build
        working-directory: client
        run: npm ci && npm run build